[[constraint]]
    name = "github.com/xgfone/go-tools"
    version = "v2.4.0"

[[constraint]]
    name = "github.com/urfave/cli"
    version = "1.91.1"

[[constraint]]
    name = "github.com/jackpal/bencode-go"
    revision = "8b8d9a9b37fcd43f365439810d725081b114af68"

[[constraint]]
    name = "github.com/axgle/mahonia"
    revision = "c528b747d92d41ca581a7acf3e604c396fc7c034"
